services:
  - type: web
    name: llama
    env: python
    region: oregon  # Change as needed
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    port: 5000
    envVars:
      - key: SERPAPI_KEY
        value: YOUR_SERPAPI_KEY
      - key: HF_TOKEN
        value: YOUR_HUGGING_FACE_TOKEN
